#!/bin/sh

# cached wheels + other elements can screw up the installation process.
# before i do this, i use 'checkmytemps' to look at all cache dirs 
# if there's wheels or other things... even empty dirs, i remove them
module load conda
conda create --clone python-3.9-20220720 --prefix=/nbhome/$USER/ians_epmt
conda activate /nbhome/$USER/ians_epmt

which pip

pip install /nbhome/epmt/epmt-4.10.0.tar.gz

return

### at the end of all of this, got the following complaints.
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray 2023.2.0 requires pandas>=1.4, but you have pandas 1.3.5 which is incompatible.
sphinx 5.0.2 requires importlib-metadata>=4.4; python_version < "3.10", but you have importlib-metadata 0.23 which is incompatible.
nbclient 0.6.6 requires jupyter-client>=6.1.5, but you have jupyter-client 5.3.4 which is incompatible.
nbclient 0.6.6 requires nbformat>=5.0, but you have nbformat 4.4.0 which is incompatible.
nbclient 0.6.6 requires traitlets>=5.2.2, but you have traitlets 4.3.3 which is incompatible.
nbclassic 0.4.3 requires jupyter-client>=6.1.1, but you have jupyter-client 5.3.4 which is incompatible.
nbclassic 0.4.3 requires Send2Trash>=1.8.0, but you have send2trash 1.5.0 which is incompatible.
jupyterlab-server 2.15.0 requires importlib-metadata>=3.6; python_version < "3.10", but you have importlib-metadata 0.23 which is incompatible.
jupyterlab-server 2.15.0 requires jinja2>=3.0.3, but you have jinja2 2.10.3 which is incompatible.
jupyter-server 1.18.1 requires jupyter-client>=6.1.12, but you have jupyter-client 5.3.4 which is incompatible.
jupyter-server 1.18.1 requires jupyter-core>=4.7.0, but you have jupyter-core 4.6.1 which is incompatible.
jupyter-server 1.18.1 requires nbconvert>=6.4.4, but you have nbconvert 5.6.1 which is incompatible.
jupyter-server 1.18.1 requires nbformat>=5.2.0, but you have nbformat 4.4.0 which is incompatible.
jupyter-server 1.18.1 requires traitlets>=5.1, but you have traitlets 4.3.3 which is incompatible.
importlib-resources 5.8.0 requires zipp>=3.1.0; python_version < "3.10", but you have zipp 0.6.0 which is incompatible.
distributed 2022.7.0 requires tornado<6.2,>=6.0.3, but you have tornado 6.2 which is incompatible.
basemap 1.3.4 requires matplotlib<3.6,>=1.5; python_version >= "3.5", but you have matplotlib 3.6.3 which is incompatible.
aiohttp 3.8.1 requires charset-normalizer<3.0,>=2.0, but you have charset-normalizer 3.0.1 which is incompatible.
```
### within conda env, `conda info -a` returns....
```

     active environment : /nbhome/Ian.Laflotte/ians_epmt
    active env location : /nbhome/Ian.Laflotte/ians_epmt
            shell level : 1
       user config file : /home/Ian.Laflotte/.condarc
 populated config files : /app/conda/miniconda/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /app/conda/miniconda  (read only)
      conda av data dir : /app/conda/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/main/linux-64
                          https://conda.anaconda.org/main/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
          package cache : /app/conda/miniconda/pkgs
                          /home/Ian.Laflotte/.conda/pkgs
       envs directories : /home/Ian.Laflotte/.conda/envs
                          /app/conda/miniconda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.9.12 Linux/3.10.0-1160.76.1.el7.x86_64 rhel/7.9 glibc/2.17
                UID:GID : 21046:70
             netrc file : None
           offline mode : False

# conda environments:
#
base                     /app/conda/miniconda
cmor                     /app/conda/miniconda/envs/cmor
cmor-3.6.1               /app/conda/miniconda/envs/cmor-3.6.1
cylc                     /app/conda/miniconda/envs/cylc
cylc-8.0.1               /app/conda/miniconda/envs/cylc-8.0.1
cylc-8.0.4               /app/conda/miniconda/envs/cylc-8.0.4
cylc-8.1.0               /app/conda/miniconda/envs/cylc-8.1.0
cylc-not-default-8.0.1   /app/conda/miniconda/envs/cylc-not-default-8.0.1
esd                      /app/conda/miniconda/envs/esd
paraview-5.10.1          /app/conda/miniconda/envs/paraview-5.10.1
pyferret-7.6.3           /app/conda/miniconda/envs/pyferret-7.6.3
python-3.9-20220720      /app/conda/miniconda/envs/python-3.9-20220720
qgis                     /app/conda/miniconda/envs/qgis
                      *  /nbhome/Ian.Laflotte/ians_epmt

sys.version: 3.9.12 | packaged by conda-forge | (main...
sys.prefix: /app/conda/miniconda
sys.executable: /app/conda/miniconda/bin/python
conda location: /app/conda/miniconda/lib/python3.9/site-packages/conda
conda-build: None
conda-env: /app/conda/miniconda/bin/conda-env
user site dirs: ~/.local/lib/python3.9

CIO_TEST: <not set>
CMAKE_PREFIX_PATH: /nbhome/Ian.Laflotte/ians_epmt:/nbhome/Ian.Laflotte/ians_epmt/x86_64-conda-linux-gnu/sysroot/usr
CONDA_BUILD_SYSROOT: /nbhome/Ian.Laflotte/ians_epmt/x86_64-conda-linux-gnu/sysroot
CONDA_DEFAULT_ENV: /nbhome/Ian.Laflotte/ians_epmt
CONDA_EXE: /app/conda/miniconda/bin/conda
CONDA_PREFIX: /nbhome/Ian.Laflotte/ians_epmt
CONDA_PROMPT_MODIFIER: (/nbhome/Ian.Laflotte/ians_epmt) 
CONDA_PYTHON_EXE: /app/conda/miniconda/bin/python
CONDA_ROOT: /app/conda/miniconda
CONDA_SHLVL: 1
CONDA_TOOLCHAIN_BUILD: x86_64-conda-linux-gnu
CONDA_TOOLCHAIN_HOST: x86_64-conda-linux-gnu
CURL_CA_BUNDLE: <not set>
GDAL_DRIVER_PATH: /nbhome/Ian.Laflotte/ians_epmt/lib/gdalplugins
GLOBUS_PATH: /usr/local/globus/6.0.1506371041
LD_LIBRARY_PATH: /usr/local/globus/6.0.1506371041/lib:/usr/local/globus/6.0.1506371041/lib64
MANPATH: /usr/local/slurm/22.05.8_el7/share/man:/usr/local/Modules/5.1.1/share/man:/home/gfdl/man:/usr/local/man:/usr/share/man
MODULEPATH: /app/conda/modulefiles:/app/spack/default/modulefiles:/app/spack/v0.15/modulefiles/linux-rhel7-x86_64:/app/spack/2023.01/modulefiles/linux-rhel7-x86_64:/usr/local/Modules/default/modulefiles:/usr/local/Modules/modulefiles:/home/fms/local/modulefiles
PATH: /app/conda/miniconda/bin:/nbhome/Ian.Laflotte/ians_epmt/bin:/app/conda/miniconda/condabin:/usr/local/slurm/22.05.8_el7/bin:/usr/local/globus/6.0.1506371041/bin:/usr/local/Modules/5.1.1/bin:/home/gfdl/bin2:/usr/local/bin:/bin:/usr/bin:.:/home/Ian.Laflotte/bin
QT_PLUGIN_PATH: /usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
UDUNITS2_XML_PATH: /nbhome/Ian.Laflotte/ians_epmt/share/udunits/udunits2.xml
X509_USER_PROXY: <set>
```
### within the conda env, `python3 -m sysconfig`
```
Platform: "linux-x86_64"
Python version: "3.9"
Current installation scheme: "posix_prefix"

Paths: 
	data = "/nbhome/Ian.Laflotte/ians_epmt"
	include = "/nbhome/Ian.Laflotte/ians_epmt/include/python3.9"
	platinclude = "/nbhome/Ian.Laflotte/ians_epmt/include/python3.9"
	platlib = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9/site-packages"
	platstdlib = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9"
	purelib = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9/site-packages"
	scripts = "/nbhome/Ian.Laflotte/ians_epmt/bin"
	stdlib = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9"

Variables: 
	ABIFLAGS = ""
	AC_APPLE_UNIVERSAL_BUILD = "0"
	AIX_BUILDDATE = "0"
	AIX_GENUINE_CPLUSPLUS = "0"
	ALT_SOABI = "0"
	ANDROID_API_LEVEL = "0"
	AR = "ar"
	ARFLAGS = "rcs"
	BASECFLAGS = "-Wno-unused-result -Wsign-compare"
	BASECPPFLAGS = "-IObjects -IInclude -IPython"
	BASEMODLIBS = ""
	BINDIR = "/nbhome/Ian.Laflotte/ians_epmt/bin"
	BINLIBDEST = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9"
	BLDLIBRARY = "libpython3.9.a"
	BLDSHARED = "gcc -pthread -B /nbhome/Ian.Laflotte/ians_epmt/compiler_compat -shared  -Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib"
	BUILDEXE = ""
	BUILDPYTHON = "python"
	BUILD_GNU_TYPE = "x86_64-conda_cos6-linux-gnu"
	BYTESTR_DEPS = "\"
	CC = "gcc -pthread -B /nbhome/Ian.Laflotte/ians_epmt/compiler_compat"
	CCSHARED = "-fPIC"
	CFLAGS = "-Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2   -isystem /nbhome/Ian.Laflotte/ians_epmt/include -fPIC -O2   -isystem /nbhome/Ian.Laflotte/ians_epmt/include "
	CFLAGSFORSHARED = ""
	CFLAGS_ALIASING = ""
	CONFIGFILES = "configure configure.ac acconfig.h pyconfig.h.in Makefile.pre.in"
	CONFIGURE_CFLAGS = "-fPIC -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include "
	CONFIGURE_CFLAGS_NODIST = "-g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden"
	CONFIGURE_CPPFLAGS = "-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include"
	CONFIGURE_LDFLAGS = "-Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib"
	CONFIGURE_LDFLAGS_NODIST = "-g"
	CONFIG_ARGS = "'--prefix=/nbhome/Ian.Laflotte/ians_epmt''--build=x86_64-conda_cos6-linux-gnu''--host=x86_64-conda_cos6-linux-gnu''--enable-ipv6''--with-ensurepip=no''--with-tzpath=/nbhome/Ian.Laflotte/ians_epmt/share/zoneinfo:/nbhome/Ian.Laflotte/ians_epmt/share/tzinfo''--with-computed-gotos''--with-system-ffi''--enable-loadable-sqlite-extensions''--with-tcltk-includes=-I/nbhome/Ian.Laflotte/ians_epmt/include''--with-tcltk-libs=-L/nbhome/Ian.Laflotte/ians_epmt/lib -ltcl8.6 -ltk8.6''--with-platlibdir=lib''--with-lto''--enable-optimizations''-oldincludedir=/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/include''--disable-shared''PROFILE_TASK=-m test --pgo''build_alias=x86_64-conda_cos6-linux-gnu''host_alias=x86_64-conda_cos6-linux-gnu''MACHDEP=linux''CC=gcc''CFLAGS= -fPIC -O2  -isystem /nbhome/Ian.Laflotte/ians_epmt/include ''LDFLAGS=   -Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib''CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include''CPP=/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/_build_env/bin/cpp''PKG_CONFIG_PATH=/nbhome/Ian.Laflotte/ians_epmt/lib/pkgconfig'"
	CONFINCLUDEDIR = "/nbhome/Ian.Laflotte/ians_epmt/include"
	CONFINCLUDEPY = "/nbhome/Ian.Laflotte/ians_epmt/include/python3.9"
	COREPYTHONPATH = ""
	COVERAGE_INFO = "/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/build-static/coverage.info"
	COVERAGE_REPORT = "/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/build-static/lcov-report"
	COVERAGE_REPORT_OPTIONS = "--no-branch-coverage --title "CPython lcov report""
	CPPFLAGS = "-IObjects -IInclude -IPython -I. -I/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include"
	CXX = "g++ -pthread -B /nbhome/Ian.Laflotte/ians_epmt/compiler_compat"
	DESTDIRS = "/nbhome/Ian.Laflotte/ians_epmt /nbhome/Ian.Laflotte/ians_epmt/lib /nbhome/Ian.Laflotte/ians_epmt/lib/python3.9 /nbhome/Ian.Laflotte/ians_epmt/lib/python3.9/lib-dynload"
	DESTLIB = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9"
	DESTPATH = ""
	DESTSHARED = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9/lib-dynload"
	DFLAGS = ""
	DIRMODE = "755"
	DIST = "README.rst ChangeLog configure configure.ac acconfig.h pyconfig.h.in Makefile.pre.in Include Lib Misc Ext-dummy"
	DISTDIRS = "Include Lib Misc Ext-dummy"
	DISTFILES = "README.rst ChangeLog configure configure.ac acconfig.h pyconfig.h.in Makefile.pre.in"
	DLINCLDIR = "."
	DLLLIBRARY = ""
	DOUBLE_IS_ARM_MIXED_ENDIAN_IEEE754 = "0"
	DOUBLE_IS_BIG_ENDIAN_IEEE754 = "0"
	DOUBLE_IS_LITTLE_ENDIAN_IEEE754 = "1"
	DTRACE = ""
	DTRACE_DEPS = "\"
	DTRACE_HEADERS = ""
	DTRACE_OBJS = ""
	DYNLOADFILE = "dynload_shlib.o"
	ENABLE_IPV6 = "1"
	ENSUREPIP = "no"
	EXE = ""
	EXEMODE = "755"
	EXPORTSFROM = ""
	EXPORTSYMS = ""
	EXTRATESTOPTS = ""
	EXT_SUFFIX = ".cpython-39-x86_64-linux-gnu.so"
	FILEMODE = "644"
	FLOAT_WORDS_BIGENDIAN = "0"
	FLOCK_NEEDS_LIBBSD = "0"
	GETPGRP_HAVE_ARG = "0"
	GITBRANCH = ""
	GITTAG = ""
	GITVERSION = ""
	GNULD = "no"
	HAVE_ACCEPT4 = "1"
	HAVE_ACOSH = "1"
	HAVE_ADDRINFO = "1"
	HAVE_ALARM = "1"
	HAVE_ALIGNED_REQUIRED = "0"
	HAVE_ALLOCA_H = "1"
	HAVE_ALTZONE = "0"
	HAVE_ASINH = "1"
	HAVE_ASM_TYPES_H = "1"
	HAVE_ATANH = "1"
	HAVE_BIND_TEXTDOMAIN_CODESET = "1"
	HAVE_BLUETOOTH_BLUETOOTH_H = "0"
	HAVE_BLUETOOTH_H = "0"
	HAVE_BROKEN_MBSTOWCS = "0"
	HAVE_BROKEN_NICE = "0"
	HAVE_BROKEN_PIPE_BUF = "0"
	HAVE_BROKEN_POLL = "0"
	HAVE_BROKEN_POSIX_SEMAPHORES = "0"
	HAVE_BROKEN_PTHREAD_SIGMASK = "0"
	HAVE_BROKEN_SEM_GETVALUE = "0"
	HAVE_BROKEN_UNSETENV = "0"
	HAVE_BUILTIN_ATOMIC = "1"
	HAVE_CHFLAGS = "0"
	HAVE_CHOWN = "1"
	HAVE_CHROOT = "1"
	HAVE_CLOCK = "1"
	HAVE_CLOCK_GETRES = "1"
	HAVE_CLOCK_GETTIME = "1"
	HAVE_CLOCK_SETTIME = "1"
	HAVE_COMPUTED_GOTOS = "1"
	HAVE_CONFSTR = "1"
	HAVE_CONIO_H = "0"
	HAVE_COPYSIGN = "1"
	HAVE_COPY_FILE_RANGE = "0"
	HAVE_CRYPT_H = "1"
	HAVE_CRYPT_R = "1"
	HAVE_CTERMID = "1"
	HAVE_CTERMID_R = "0"
	HAVE_CURSES_FILTER = "1"
	HAVE_CURSES_H = "1"
	HAVE_CURSES_HAS_KEY = "1"
	HAVE_CURSES_IMMEDOK = "1"
	HAVE_CURSES_IS_PAD = "1"
	HAVE_CURSES_IS_TERM_RESIZED = "1"
	HAVE_CURSES_RESIZETERM = "1"
	HAVE_CURSES_RESIZE_TERM = "1"
	HAVE_CURSES_SYNCOK = "1"
	HAVE_CURSES_TYPEAHEAD = "1"
	HAVE_CURSES_USE_ENV = "1"
	HAVE_CURSES_WCHGAT = "1"
	HAVE_DECL_ISFINITE = "1"
	HAVE_DECL_ISINF = "1"
	HAVE_DECL_ISNAN = "1"
	HAVE_DECL_RTLD_DEEPBIND = "1"
	HAVE_DECL_RTLD_GLOBAL = "1"
	HAVE_DECL_RTLD_LAZY = "1"
	HAVE_DECL_RTLD_LOCAL = "1"
	HAVE_DECL_RTLD_MEMBER = "0"
	HAVE_DECL_RTLD_NODELETE = "1"
	HAVE_DECL_RTLD_NOLOAD = "1"
	HAVE_DECL_RTLD_NOW = "1"
	HAVE_DECL_TZNAME = "0"
	HAVE_DEVICE_MACROS = "1"
	HAVE_DEV_PTC = "0"
	HAVE_DEV_PTMX = "1"
	HAVE_DIRECT_H = "0"
	HAVE_DIRENT_D_TYPE = "1"
	HAVE_DIRENT_H = "1"
	HAVE_DIRFD = "1"
	HAVE_DLFCN_H = "1"
	HAVE_DLOPEN = "1"
	HAVE_DUP2 = "1"
	HAVE_DUP3 = "1"
	HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH = "0"
	HAVE_DYNAMIC_LOADING = "1"
	HAVE_ENDIAN_H = "1"
	HAVE_EPOLL = "1"
	HAVE_EPOLL_CREATE1 = "1"
	HAVE_ERF = "1"
	HAVE_ERFC = "1"
	HAVE_ERRNO_H = "1"
	HAVE_EXECV = "1"
	HAVE_EXPLICIT_BZERO = "0"
	HAVE_EXPLICIT_MEMSET = "0"
	HAVE_EXPM1 = "1"
	HAVE_FACCESSAT = "1"
	HAVE_FCHDIR = "1"
	HAVE_FCHMOD = "1"
	HAVE_FCHMODAT = "1"
	HAVE_FCHOWN = "1"
	HAVE_FCHOWNAT = "1"
	HAVE_FCNTL_H = "1"
	HAVE_FDATASYNC = "1"
	HAVE_FDOPENDIR = "1"
	HAVE_FDWALK = "0"
	HAVE_FEXECVE = "1"
	HAVE_FINITE = "1"
	HAVE_FLOCK = "1"
	HAVE_FORK = "1"
	HAVE_FORKPTY = "1"
	HAVE_FPATHCONF = "1"
	HAVE_FSEEK64 = "0"
	HAVE_FSEEKO = "1"
	HAVE_FSTATAT = "1"
	HAVE_FSTATVFS = "1"
	HAVE_FSYNC = "1"
	HAVE_FTELL64 = "0"
	HAVE_FTELLO = "1"
	HAVE_FTIME = "1"
	HAVE_FTRUNCATE = "1"
	HAVE_FUTIMENS = "1"
	HAVE_FUTIMES = "1"
	HAVE_FUTIMESAT = "1"
	HAVE_GAI_STRERROR = "1"
	HAVE_GAMMA = "1"
	HAVE_GCC_ASM_FOR_MC68881 = "0"
	HAVE_GCC_ASM_FOR_X64 = "1"
	HAVE_GCC_ASM_FOR_X87 = "1"
	HAVE_GCC_UINT128_T = "1"
	HAVE_GETADDRINFO = "1"
	HAVE_GETC_UNLOCKED = "1"
	HAVE_GETENTROPY = "0"
	HAVE_GETGRGID_R = "1"
	HAVE_GETGRNAM_R = "1"
	HAVE_GETGROUPLIST = "1"
	HAVE_GETGROUPS = "1"
	HAVE_GETHOSTBYNAME = "0"
	HAVE_GETHOSTBYNAME_R = "1"
	HAVE_GETHOSTBYNAME_R_3_ARG = "0"
	HAVE_GETHOSTBYNAME_R_5_ARG = "0"
	HAVE_GETHOSTBYNAME_R_6_ARG = "1"
	HAVE_GETITIMER = "1"
	HAVE_GETLOADAVG = "1"
	HAVE_GETLOGIN = "1"
	HAVE_GETNAMEINFO = "1"
	HAVE_GETPAGESIZE = "1"
	HAVE_GETPEERNAME = "1"
	HAVE_GETPGID = "1"
	HAVE_GETPGRP = "1"
	HAVE_GETPID = "1"
	HAVE_GETPRIORITY = "1"
	HAVE_GETPWENT = "1"
	HAVE_GETPWNAM_R = "1"
	HAVE_GETPWUID_R = "1"
	HAVE_GETRANDOM = "0"
	HAVE_GETRANDOM_SYSCALL = "0"
	HAVE_GETRESGID = "1"
	HAVE_GETRESUID = "1"
	HAVE_GETSID = "1"
	HAVE_GETSPENT = "1"
	HAVE_GETSPNAM = "1"
	HAVE_GETWD = "1"
	HAVE_GLIBC_MEMMOVE_BUG = "0"
	HAVE_GRP_H = "1"
	HAVE_HSTRERROR = "1"
	HAVE_HTOLE64 = "1"
	HAVE_HYPOT = "1"
	HAVE_IEEEFP_H = "0"
	HAVE_IF_NAMEINDEX = "1"
	HAVE_INET_ATON = "1"
	HAVE_INET_PTON = "1"
	HAVE_INITGROUPS = "1"
	HAVE_INTTYPES_H = "1"
	HAVE_IO_H = "0"
	HAVE_IPA_PURE_CONST_BUG = "0"
	HAVE_KILL = "1"
	HAVE_KILLPG = "1"
	HAVE_KQUEUE = "0"
	HAVE_LANGINFO_H = "1"
	HAVE_LARGEFILE_SUPPORT = "0"
	HAVE_LCHFLAGS = "0"
	HAVE_LCHMOD = "0"
	HAVE_LCHOWN = "1"
	HAVE_LGAMMA = "1"
	HAVE_LIBDL = "1"
	HAVE_LIBDLD = "0"
	HAVE_LIBIEEE = "0"
	HAVE_LIBINTL_H = "1"
	HAVE_LIBREADLINE = "1"
	HAVE_LIBRESOLV = "0"
	HAVE_LIBSENDFILE = "0"
	HAVE_LIBUTIL_H = "0"
	HAVE_LIBUUID = "1"
	HAVE_LINK = "1"
	HAVE_LINKAT = "1"
	HAVE_LINUX_AUXVEC_H = "1"
	HAVE_LINUX_CAN_BCM_H = "0"
	HAVE_LINUX_CAN_H = "1"
	HAVE_LINUX_CAN_J1939_H = "0"
	HAVE_LINUX_CAN_RAW_FD_FRAMES = "0"
	HAVE_LINUX_CAN_RAW_H = "1"
	HAVE_LINUX_CAN_RAW_JOIN_FILTERS = "0"
	HAVE_LINUX_MEMFD_H = "0"
	HAVE_LINUX_NETLINK_H = "1"
	HAVE_LINUX_QRTR_H = "0"
	HAVE_LINUX_RANDOM_H = "1"
	HAVE_LINUX_TIPC_H = "1"
	HAVE_LINUX_VM_SOCKETS_H = "0"
	HAVE_LINUX_WAIT_H = "1"
	HAVE_LOCKF = "1"
	HAVE_LOG1P = "1"
	HAVE_LOG2 = "1"
	HAVE_LONG_DOUBLE = "1"
	HAVE_LSTAT = "1"
	HAVE_LUTIMES = "1"
	HAVE_MADVISE = "1"
	HAVE_MAKEDEV = "1"
	HAVE_MBRTOWC = "1"
	HAVE_MEMFD_CREATE = "0"
	HAVE_MEMORY_H = "1"
	HAVE_MEMRCHR = "1"
	HAVE_MKDIRAT = "1"
	HAVE_MKFIFO = "1"
	HAVE_MKFIFOAT = "1"
	HAVE_MKNOD = "1"
	HAVE_MKNODAT = "1"
	HAVE_MKTIME = "1"
	HAVE_MMAP = "1"
	HAVE_MREMAP = "1"
	HAVE_NCURSES_H = "1"
	HAVE_NDIR_H = "0"
	HAVE_NETPACKET_PACKET_H = "1"
	HAVE_NET_IF_H = "1"
	HAVE_NICE = "1"
	HAVE_NON_UNICODE_WCHAR_T_REPRESENTATION = "0"
	HAVE_OPENAT = "1"
	HAVE_OPENPTY = "1"
	HAVE_PATHCONF = "1"
	HAVE_PAUSE = "1"
	HAVE_PIPE2 = "1"
	HAVE_PLOCK = "0"
	HAVE_POLL = "1"
	HAVE_POLL_H = "1"
	HAVE_POSIX_FADVISE = "1"
	HAVE_POSIX_FALLOCATE = "1"
	HAVE_POSIX_SPAWN = "1"
	HAVE_POSIX_SPAWNP = "1"
	HAVE_PREAD = "1"
	HAVE_PREADV = "1"
	HAVE_PREADV2 = "0"
	HAVE_PRLIMIT = "0"
	HAVE_PROCESS_H = "0"
	HAVE_PROTOTYPES = "1"
	HAVE_PTHREAD_CONDATTR_SETCLOCK = "1"
	HAVE_PTHREAD_DESTRUCTOR = "0"
	HAVE_PTHREAD_GETCPUCLOCKID = "1"
	HAVE_PTHREAD_H = "1"
	HAVE_PTHREAD_INIT = "0"
	HAVE_PTHREAD_KILL = "1"
	HAVE_PTHREAD_SIGMASK = "1"
	HAVE_PTY_H = "1"
	HAVE_PWRITE = "1"
	HAVE_PWRITEV = "1"
	HAVE_PWRITEV2 = "0"
	HAVE_READLINK = "1"
	HAVE_READLINKAT = "1"
	HAVE_READV = "1"
	HAVE_REALPATH = "1"
	HAVE_RENAMEAT = "1"
	HAVE_RL_APPEND_HISTORY = "1"
	HAVE_RL_CATCH_SIGNAL = "1"
	HAVE_RL_COMPLETION_APPEND_CHARACTER = "1"
	HAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK = "1"
	HAVE_RL_COMPLETION_MATCHES = "1"
	HAVE_RL_COMPLETION_SUPPRESS_APPEND = "1"
	HAVE_RL_PRE_INPUT_HOOK = "1"
	HAVE_RL_RESIZE_TERMINAL = "1"
	HAVE_ROUND = "1"
	HAVE_RTPSPAWN = "0"
	HAVE_SCHED_GET_PRIORITY_MAX = "1"
	HAVE_SCHED_H = "1"
	HAVE_SCHED_RR_GET_INTERVAL = "1"
	HAVE_SCHED_SETAFFINITY = "1"
	HAVE_SCHED_SETPARAM = "1"
	HAVE_SCHED_SETSCHEDULER = "1"
	HAVE_SEM_CLOCKWAIT = "0"
	HAVE_SEM_GETVALUE = "1"
	HAVE_SEM_OPEN = "1"
	HAVE_SEM_TIMEDWAIT = "1"
	HAVE_SEM_UNLINK = "1"
	HAVE_SENDFILE = "1"
	HAVE_SETEGID = "1"
	HAVE_SETEUID = "1"
	HAVE_SETGID = "1"
	HAVE_SETGROUPS = "1"
	HAVE_SETHOSTNAME = "1"
	HAVE_SETITIMER = "1"
	HAVE_SETLOCALE = "1"
	HAVE_SETPGID = "1"
	HAVE_SETPGRP = "1"
	HAVE_SETPRIORITY = "1"
	HAVE_SETREGID = "1"
	HAVE_SETRESGID = "1"
	HAVE_SETRESUID = "1"
	HAVE_SETREUID = "1"
	HAVE_SETSID = "1"
	HAVE_SETUID = "1"
	HAVE_SETVBUF = "1"
	HAVE_SHADOW_H = "1"
	HAVE_SHM_OPEN = "1"
	HAVE_SHM_UNLINK = "1"
	HAVE_SIGACTION = "1"
	HAVE_SIGALTSTACK = "1"
	HAVE_SIGFILLSET = "1"
	HAVE_SIGINFO_T_SI_BAND = "1"
	HAVE_SIGINTERRUPT = "1"
	HAVE_SIGNAL_H = "1"
	HAVE_SIGPENDING = "1"
	HAVE_SIGRELSE = "1"
	HAVE_SIGTIMEDWAIT = "1"
	HAVE_SIGWAIT = "1"
	HAVE_SIGWAITINFO = "1"
	HAVE_SNPRINTF = "1"
	HAVE_SOCKADDR_ALG = "0"
	HAVE_SOCKADDR_SA_LEN = "0"
	HAVE_SOCKADDR_STORAGE = "1"
	HAVE_SOCKETPAIR = "1"
	HAVE_SPAWN_H = "1"
	HAVE_SSIZE_T = "1"
	HAVE_STATVFS = "1"
	HAVE_STAT_TV_NSEC = "1"
	HAVE_STAT_TV_NSEC2 = "0"
	HAVE_STDARG_PROTOTYPES = "1"
	HAVE_STDINT_H = "1"
	HAVE_STDLIB_H = "1"
	HAVE_STD_ATOMIC = "1"
	HAVE_STRDUP = "1"
	HAVE_STRFTIME = "1"
	HAVE_STRINGS_H = "1"
	HAVE_STRING_H = "1"
	HAVE_STRLCPY = "0"
	HAVE_STROPTS_H = "0"
	HAVE_STRSIGNAL = "1"
	HAVE_STRUCT_PASSWD_PW_GECOS = "1"
	HAVE_STRUCT_PASSWD_PW_PASSWD = "1"
	HAVE_STRUCT_STAT_ST_BIRTHTIME = "0"
	HAVE_STRUCT_STAT_ST_BLKSIZE = "1"
	HAVE_STRUCT_STAT_ST_BLOCKS = "1"
	HAVE_STRUCT_STAT_ST_FLAGS = "0"
	HAVE_STRUCT_STAT_ST_GEN = "0"
	HAVE_STRUCT_STAT_ST_RDEV = "1"
	HAVE_STRUCT_TM_TM_ZONE = "1"
	HAVE_SYMLINK = "1"
	HAVE_SYMLINKAT = "1"
	HAVE_SYNC = "1"
	HAVE_SYSCONF = "1"
	HAVE_SYSEXITS_H = "1"
	HAVE_SYS_AUDIOIO_H = "0"
	HAVE_SYS_AUXV_H = "0"
	HAVE_SYS_BSDTTY_H = "0"
	HAVE_SYS_DEVPOLL_H = "0"
	HAVE_SYS_DIR_H = "0"
	HAVE_SYS_ENDIAN_H = "0"
	HAVE_SYS_EPOLL_H = "1"
	HAVE_SYS_EVENT_H = "0"
	HAVE_SYS_FILE_H = "1"
	HAVE_SYS_IOCTL_H = "1"
	HAVE_SYS_KERN_CONTROL_H = "0"
	HAVE_SYS_LOADAVG_H = "0"
	HAVE_SYS_LOCK_H = "0"
	HAVE_SYS_MEMFD_H = "0"
	HAVE_SYS_MKDEV_H = "0"
	HAVE_SYS_MMAN_H = "1"
	HAVE_SYS_MODEM_H = "0"
	HAVE_SYS_NDIR_H = "0"
	HAVE_SYS_PARAM_H = "1"
	HAVE_SYS_POLL_H = "1"
	HAVE_SYS_RANDOM_H = "0"
	HAVE_SYS_RESOURCE_H = "1"
	HAVE_SYS_SELECT_H = "1"
	HAVE_SYS_SENDFILE_H = "1"
	HAVE_SYS_SOCKET_H = "1"
	HAVE_SYS_STATVFS_H = "1"
	HAVE_SYS_STAT_H = "1"
	HAVE_SYS_SYSCALL_H = "1"
	HAVE_SYS_SYSMACROS_H = "1"
	HAVE_SYS_SYS_DOMAIN_H = "0"
	HAVE_SYS_TERMIO_H = "0"
	HAVE_SYS_TIMES_H = "1"
	HAVE_SYS_TIME_H = "1"
	HAVE_SYS_TYPES_H = "1"
	HAVE_SYS_UIO_H = "1"
	HAVE_SYS_UN_H = "1"
	HAVE_SYS_UTSNAME_H = "1"
	HAVE_SYS_WAIT_H = "1"
	HAVE_SYS_XATTR_H = "1"
	HAVE_TCGETPGRP = "1"
	HAVE_TCSETPGRP = "1"
	HAVE_TEMPNAM = "1"
	HAVE_TERMIOS_H = "1"
	HAVE_TERM_H = "1"
	HAVE_TGAMMA = "1"
	HAVE_TIMEGM = "1"
	HAVE_TIMES = "1"
	HAVE_TMPFILE = "1"
	HAVE_TMPNAM = "1"
	HAVE_TMPNAM_R = "1"
	HAVE_TM_ZONE = "1"
	HAVE_TRUNCATE = "1"
	HAVE_TZNAME = "0"
	HAVE_UCS4_TCL = "0"
	HAVE_UNAME = "1"
	HAVE_UNISTD_H = "1"
	HAVE_UNLINKAT = "1"
	HAVE_USABLE_WCHAR_T = "0"
	HAVE_UTIL_H = "0"
	HAVE_UTIMENSAT = "1"
	HAVE_UTIMES = "1"
	HAVE_UTIME_H = "1"
	HAVE_UUID_CREATE = "0"
	HAVE_UUID_ENC_BE = "0"
	HAVE_UUID_GENERATE_TIME_SAFE = "1"
	HAVE_UUID_H = "1"
	HAVE_UUID_UUID_H = "1"
	HAVE_WAIT3 = "1"
	HAVE_WAIT4 = "1"
	HAVE_WAITID = "1"
	HAVE_WAITPID = "1"
	HAVE_WCHAR_H = "1"
	HAVE_WCSCOLL = "1"
	HAVE_WCSFTIME = "1"
	HAVE_WCSXFRM = "1"
	HAVE_WMEMCMP = "1"
	HAVE_WORKING_TZSET = "1"
	HAVE_WRITEV = "1"
	HAVE_X509_VERIFY_PARAM_SET1_HOST = "1"
	HAVE_ZLIB_COPY = "1"
	HAVE__GETPTY = "0"
	HOST_GNU_TYPE = "x86_64-conda_cos6-linux-gnu"
	INCLDIRSTOMAKE = "/nbhome/Ian.Laflotte/ians_epmt/include /nbhome/Ian.Laflotte/ians_epmt/include /nbhome/Ian.Laflotte/ians_epmt/include/python3.9 /nbhome/Ian.Laflotte/ians_epmt/include/python3.9"
	INCLUDEDIR = "/nbhome/Ian.Laflotte/ians_epmt/include"
	INCLUDEPY = "/nbhome/Ian.Laflotte/ians_epmt/include/python3.9"
	INSTALL = "/usr/bin/install -c"
	INSTALL_DATA = "/usr/bin/install -c -m 644"
	INSTALL_PROGRAM = "/usr/bin/install -c"
	INSTALL_SCRIPT = "/usr/bin/install -c"
	INSTALL_SHARED = "/usr/bin/install -c -m 755"
	INSTSONAME = "libpython3.9.a"
	IO_H = "Modules/_io/_iomodule.h"
	IO_OBJS = "\"
	LDCXXSHARED = "g++ -pthread -B /nbhome/Ian.Laflotte/ians_epmt/compiler_compat -shared"
	LDFLAGS = "-Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib"
	LDLIBRARY = "libpython3.9.a"
	LDLIBRARYDIR = ""
	LDSHARED = "gcc -pthread -B /nbhome/Ian.Laflotte/ians_epmt/compiler_compat -shared  -Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib"
	LDVERSION = "3.9"
	LIBC = ""
	LIBDEST = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9"
	LIBDIR = "/nbhome/Ian.Laflotte/ians_epmt/lib"
	LIBFFI_INCLUDEDIR = "/nbhome/Ian.Laflotte/ians_epmt/include"
	LIBM = "-lm"
	LIBOBJDIR = "Python/"
	LIBOBJS = ""
	LIBPC = "/nbhome/Ian.Laflotte/ians_epmt/lib/pkgconfig"
	LIBPL = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9/config-3.9-x86_64-linux-gnu"
	LIBPYTHON = ""
	LIBRARY = "libpython3.9.a"
	LIBRARY_OBJS = "\"
	LIBRARY_OBJS_OMIT_FROZEN = "\"
	LIBS = "-lcrypt -lpthread -ldl  -lutil -lrt -lm"
	LIBSUBDIRS = "tkinter tkinter/test tkinter/test/test_tkinter \"
	LINKCC = "gcc -pthread -B /nbhome/Ian.Laflotte/ians_epmt/compiler_compat"
	LINKFORSHARED = "-Xlinker -export-dynamic"
	LIPO_32BIT_FLAGS = ""
	LIPO_INTEL64_FLAGS = ""
	LLVM_PROF_ERR = "no"
	LLVM_PROF_FILE = ""
	LLVM_PROF_MERGER = "true"
	LN = "ln"
	LOCALMODLIBS = ""
	MACHDEP = "linux"
	MACHDEP_OBJS = ""
	MACHDESTLIB = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9"
	MACOSX_DEPLOYMENT_TARGET = ""
	MAINCC = "gcc -pthread -B /nbhome/Ian.Laflotte/ians_epmt/compiler_compat"
	MAJOR_IN_MKDEV = "0"
	MAJOR_IN_SYSMACROS = "0"
	MAKESETUP = "/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Modules/makesetup"
	MANDIR = "/nbhome/Ian.Laflotte/ians_epmt/share/man"
	MKDIR_P = "/usr/bin/mkdir -p"
	MODBUILT_NAMES = "posix  errno  pwd  _sre  _codecs  _weakref  _functools  _operator  _collections  _abc  itertools  atexit  _signal  _stat  time  _thread  _locale  _io  faulthandler  _tracemalloc  _peg_parser  _symtable  xxsubtype"
	MODDISABLED_NAMES = ""
	MODLIBS = ""
	MODOBJS = "Modules/posixmodule.o  Modules/errnomodule.o  Modules/pwdmodule.o  Modules/_sre.o  Modules/_codecsmodule.o  Modules/_weakref.o  Modules/_functoolsmodule.o  Modules/_operator.o  Modules/_collectionsmodule.o  Modules/_abc.o  Modules/itertoolsmodule.o  Modules/atexitmodule.o  Modules/signalmodule.o  Modules/_stat.o  Modules/timemodule.o  Modules/_threadmodule.o  Modules/_localemodule.o  Modules/_iomodule.o Modules/iobase.o Modules/fileio.o Modules/bytesio.o Modules/bufferedio.o Modules/textio.o Modules/stringio.o  Modules/faulthandler.o  Modules/_tracemalloc.o  Modules/_peg_parser.o  Modules/symtablemodule.o  Modules/xxsubtype.o"
	MODULE_OBJS = "\"
	MULTIARCH = "x86_64-linux-gnu"
	MULTIARCH_CPPFLAGS = "-DMULTIARCH=\"x86_64-linux-gnu\""
	MVWDELCH_IS_EXPRESSION = "1"
	NO_AS_NEEDED = "-Wl,--no-as-needed"
	OBJECT_OBJS = "\"
	OPENSSL_INCLUDES = "-I/nbhome/Ian.Laflotte/ians_epmt/include"
	OPENSSL_LDFLAGS = "-L/nbhome/Ian.Laflotte/ians_epmt/lib"
	OPENSSL_LIBS = "-lssl -lcrypto"
	OPT = "-DNDEBUG -fwrapv -O2 -Wall"
	OTHER_LIBTOOL_OPT = ""
	PACKAGE_BUGREPORT = "0"
	PACKAGE_NAME = "0"
	PACKAGE_STRING = "0"
	PACKAGE_TARNAME = "0"
	PACKAGE_URL = "0"
	PACKAGE_VERSION = "0"
	PARSER_HEADERS = "\"
	PARSER_OBJS = "\ \ Parser/myreadline.o Parser/parsetok.o Parser/tokenizer.o"
	PEGEN_HEADERS = "\"
	PEGEN_OBJS = "\"
	PGO_PROF_GEN_FLAG = "-fprofile-generate"
	PGO_PROF_USE_FLAG = ""
	PLATLIBDIR = "lib"
	POBJS = "\"
	POSIX_SEMAPHORES_NOT_ENABLED = "0"
	PROFILE_TASK = "-m test --pgo"
	PTHREAD_KEY_T_IS_COMPATIBLE_WITH_INT = "1"
	PTHREAD_SYSTEM_SCHED_SUPPORTED = "1"
	PURIFY = ""
	PY3LIBRARY = ""
	PYLONG_BITS_IN_DIGIT = "0"
	PYTHON = "python"
	PYTHONFRAMEWORK = ""
	PYTHONFRAMEWORKDIR = "no-framework"
	PYTHONFRAMEWORKINSTALLDIR = ""
	PYTHONFRAMEWORKPREFIX = ""
	PYTHONPATH = ""
	PYTHON_FOR_BUILD = "./python -E"
	PYTHON_HEADERS = "\"
	PYTHON_OBJS = "\"
	PY_BUILD_ENVIRON = ""
	PY_BUILTIN_HASHLIB_HASHES = ""md5,sha1,sha256,sha512,sha3,blake2""
	PY_BUILTIN_MODULE_CFLAGS = "-Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall   -fPIC  -O2   -isystem /nbhome/Ian.Laflotte/ians_epmt/include -fPIC -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden  -I/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Include/internal -IObjects -IInclude -IPython -I. -I/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include -DPy_BUILD_CORE_BUILTIN"
	PY_CFLAGS = "-Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2   -isystem /nbhome/Ian.Laflotte/ians_epmt/include -fPIC -O2   -isystem /nbhome/Ian.Laflotte/ians_epmt/include "
	PY_CFLAGS_NODIST = "-g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden   -I/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Include/internal"
	PY_COERCE_C_LOCALE = "1"
	PY_CORE_CFLAGS = "-Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall    -fPIC -O2  -isystem /nbhome/Ian.Laflotte/ians_epmt/include -fPIC -O2  -isystem /nbhome/Ian.Laflotte/ians_epmt/include -g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -I/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Include/internal -IObjects -IInclude -IPython -I. -I/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include -DPy_BUILD_CORE"
	PY_CORE_LDFLAGS = "-Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib -g"
	PY_CPPFLAGS = "-IObjects -IInclude -IPython -I. -I/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include"
	PY_FORMAT_SIZE_T = ""z""
	PY_LDFLAGS = "-Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/nbhome/Ian.Laflotte/ians_epmt/lib -Wl,-rpath-link,/nbhome/Ian.Laflotte/ians_epmt/lib -L/nbhome/Ian.Laflotte/ians_epmt/lib"
	PY_LDFLAGS_NODIST = "-g"
	PY_SSL_DEFAULT_CIPHERS = "1"
	PY_SSL_DEFAULT_CIPHER_STRING = "0"
	PY_STDMODULE_CFLAGS = "-Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall   -fPIC  -O2   -isystem /nbhome/Ian.Laflotte/ians_epmt/include -fPIC -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden  -I/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Include/internal -IObjects -IInclude -IPython -I. -I/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nbhome/Ian.Laflotte/ians_epmt/include -I/nbhome/Ian.Laflotte/ians_epmt/include"
	Py_DEBUG = "0"
	Py_ENABLE_SHARED = "0"
	Py_HASH_ALGORITHM = "0"
	Py_TRACE_REFS = "0"
	QUICKTESTOPTS = "-x test_subprocess test_io test_lib2to3 \"
	READELF = "readelf"
	RESSRCDIR = "Mac/Resources/framework"
	RETSIGTYPE = "void"
	RUNSHARED = ""
	SCRIPTDIR = "/nbhome/Ian.Laflotte/ians_epmt/lib"
	SETPGRP_HAVE_ARG = "0"
	SHELL = "/bin/sh"
	SHLIBS = "-lcrypt -lpthread -ldl  -lutil -lrt -lm"
	SHLIB_SUFFIX = ".so"
	SHM_NEEDS_LIBRT = "0"
	SIGNED_RIGHT_SHIFT_ZERO_FILLS = "0"
	SITEPATH = ""
	SIZEOF_DOUBLE = "8"
	SIZEOF_FLOAT = "4"
	SIZEOF_FPOS_T = "16"
	SIZEOF_INT = "4"
	SIZEOF_LONG = "8"
	SIZEOF_LONG_DOUBLE = "16"
	SIZEOF_LONG_LONG = "8"
	SIZEOF_OFF_T = "8"
	SIZEOF_PID_T = "4"
	SIZEOF_PTHREAD_KEY_T = "4"
	SIZEOF_PTHREAD_T = "8"
	SIZEOF_SHORT = "2"
	SIZEOF_SIZE_T = "8"
	SIZEOF_TIME_T = "8"
	SIZEOF_UINTPTR_T = "8"
	SIZEOF_VOID_P = "8"
	SIZEOF_WCHAR_T = "4"
	SIZEOF__BOOL = "1"
	SO = ".cpython-39-x86_64-linux-gnu.so"
	SOABI = "cpython-39-x86_64-linux-gnu"
	SRCDIRS = "Parser Parser/pegen Objects Python Modules Modules/_io Programs"
	SRC_GDB_HOOKS = "/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Tools/gdb/libpython.py"
	STDC_HEADERS = "1"
	STRICT_SYSV_CURSES = "/* Don't use ncurses extensions */"
	STRIPFLAG = "-s"
	SUBDIRS = ""
	SUBDIRSTOO = "Include Lib Misc"
	SYSLIBS = "-lm"
	SYS_SELECT_WITH_SYS_TIME = "1"
	TCLTK_INCLUDES = "-I/nbhome/Ian.Laflotte/ians_epmt/include"
	TCLTK_LIBS = "-L/nbhome/Ian.Laflotte/ians_epmt/lib -ltcl8.6 -ltk8.6"
	TESTOPTS = ""
	TESTPATH = ""
	TESTPYTHON = "./python"
	TESTPYTHONOPTS = ""
	TESTRUNNER = "./python /home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Tools/scripts/run_tests.py"
	TESTTIMEOUT = "1200"
	TIMEMODULE_LIB = "rt"
	TIME_WITH_SYS_TIME = "1"
	TM_IN_SYS_TIME = "0"
	TZPATH = "/nbhome/Ian.Laflotte/ians_epmt/share/zoneinfo:/nbhome/Ian.Laflotte/ians_epmt/share/tzinfo"
	UNICODE_DEPS = "\"
	UNIVERSALSDK = ""
	UPDATE_FILE = "python3 /home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/Tools/scripts/update_file.py"
	USE_COMPUTED_GOTOS = "1"
	VERSION = "3.9"
	VPATH = "/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work"
	WINDOW_HAS_FLAGS = "1"
	WITH_DECIMAL_CONTEXTVAR = "1"
	WITH_DOC_STRINGS = "1"
	WITH_DTRACE = "0"
	WITH_DYLD = "0"
	WITH_LIBINTL = "0"
	WITH_NEXT_FRAMEWORK = "0"
	WITH_PYMALLOC = "1"
	WITH_VALGRIND = "0"
	X87_DOUBLE_ROUNDING = "0"
	XMLLIBSUBDIRS = "xml xml/dom xml/etree xml/parsers xml/sax"
	abiflags = ""
	abs_builddir = "/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work/build-static"
	abs_srcdir = "/home/conda/feedstock_root/build_artifacts/python-split_1669106039424/work"
	base = "/nbhome/Ian.Laflotte/ians_epmt"
	datarootdir = "/nbhome/Ian.Laflotte/ians_epmt/share"
	exec_prefix = "/nbhome/Ian.Laflotte/ians_epmt"
	installed_base = "/nbhome/Ian.Laflotte/ians_epmt"
	installed_platbase = "/nbhome/Ian.Laflotte/ians_epmt"
	platbase = "/nbhome/Ian.Laflotte/ians_epmt"
	platlibdir = "lib"
	prefix = "/nbhome/Ian.Laflotte/ians_epmt"
	projectbase = "/nbhome/Ian.Laflotte/ians_epmt/bin"
	py_version = "3.9.15"
	py_version_nodot = "39"
	py_version_short = "3.9"
	srcdir = "/nbhome/Ian.Laflotte/ians_epmt/lib/python3.9/config-3.9-x86_64-linux-gnu"
	userbase = "/home/Ian.Laflotte/.local"
```
