variables:
  POSTGRES_DB: "EPMT"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "example"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip

services:
  - postgres:9.5


build:python3:
  # image: python:3.7.4
  # script: # Modify the commands below to build your repository.
  #   - python3 -V
  #   - pip3 install -r requirements.txt.py3
  #   - apt-get update && apt-get install -y csh tcsh
  #   - python3 -m py_compile epmt *.py orm/*/*.py		# Compile everything
  #   - test/run --no-compose
  image: centos:7
  script:
    - yum install -y unzip bash tcsh nc curl make git gcc postgresql-devel zlib-devel bzip2 bzip2-devel readline-devel sqlite-devel openssl-devel xz xz-devel libffi-devel
    - (cd /usr/src && echo "downloading sqlite3" && curl -o sqlite-amalgamation-3300100.zip https://www.sqlite.org/2019/sqlite-amalgamation-3300100.zip && unzip sqlite-amalgamation-3300100.zip && echo "building libsqlite3 with json1 and other useful extensions" && cd sqlite-amalgamation-3300100 && gcc -shared -fPIC -O2  -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_MAX_VARIABLE_NUMBER=9999 sqlite3.c -o libsqlite3.so)
    - (cd /usr/src && echo "downloading python" && curl -o Python-3.7.4.tgz https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz && tar xzf Python-3.7.4.tgz && cd Python-3.7.4 && echo "building python3" && ./configure --enable-optimizations --enable-loadable-sqlite-extensions --with-libs=/usr/src/sqlite-amalgamation-3300100/libsqlite3.so && make --silent install > /dev/null)
    - python3 -V && pip3 install -r requirements.txt.py3 && python3 -m py_compile epmt *.py orm/*/*.py
    - test/run --no-compose
