variables:
  POSTGRES_DB: "EPMT"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "example"
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#cache:
#  paths:
#    - .cache/pip

services:
  - postgres:9.5


build:python3:
  image: python:3.7.4
  script: # Modify the commands below to build your repository.
    - python3 -V
    - pip3 install -r requirements.txt.py3
    - apt-get update && apt-get install -y csh tcsh make
    - python3 -m py_compile epmt *.py orm/*/*.py		# Compile everything
    - test/run
