image: python:2.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
          - apt-get update && apt-get install -y csh tcsh
          - rm -f settings.py; ln -s settings/settings_sqlite_inmem.py settings.py  # Setup in mem sqlite
          - python -m py_compile epmt *.py models/*.py		# Compile everything
          - env -i PATH=${PWD}:${PATH} /bin/bash -x epmt-check.anysh
          - env -i PATH=${PWD}:${PATH} /bin/sh -x epmt-check.anysh
          - env -i PATH=${PWD}:${PATH} /bin/tcsh -v epmt-check.anysh
          - env -i PATH=${PWD}:${PATH} /bin/csh -v epmt-check.anysh
          #- env -i PATH=${PWD}:${PATH} /bin/csh -ve epmt-example.csh
          - env -i PATH=${PWD}:${PATH} /bin/bash -Eeux epmt-example.anysh
          - env -i PATH=${PWD}:${PATH} /bin/bash epmt-check-stage-submit.sh
          - env -i PATH=${PWD}:${PATH} python -m unittest discover -s test -v
