image: python:2.7.13

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
          - rm -f settings.py; ln -s settings/settings_sqlite_inmem.py settings.py  # Setup in mem sqlite
          - python -m py_compile epmt *.py models/*.py		# Compile everything
          - PAPIEX_OUTPUT=/tmp/epmt/ SLURM_JOB_ID=1  ./epmt -h >/dev/null		# help path 1
          - PAPIEX_OUTPUT=/tmp/epmt/ SLURM_JOB_ID=1 ./epmt help >/dev/null		# help path 2
          - PAPIEX_OUTPUT=/tmp/epmt/ SLURM_JOB_ID=1 ./epmt start 		# Generate prolog
          - PAPIEX_OUTPUT=/tmp/epmt/ SLURM_JOB_ID=1 ./epmt source >/dev/null # Print shell command
          - PAPIEX_OUTPUT=/tmp/epmt/ SLURM_JOB_ID=1 ./epmt run sleep 1	# Run command
          - PAPIEX_OUTPUT=/tmp/epmt/ SLURM_JOB_ID=1 ./epmt stop   	  	# Generate epilog and append
          - PAPIEX_OUTPUT=/tmp/epmt/ SLURM_JOB_ID=1 ./epmt dump   		# Parse/print job_metadata
          - PAPIEX_OUTPUT=/tmp/epmt/ SLURM_JOB_ID=1 ./epmt stage		# Move to medium term storage
#          - PAPIEX_OUTPUT=/tmp/epmt/ SLURM_JOB_ID=1 ./epmt submit 		# Submit
