image: python:2.7.13

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
        - pip install -r requirements.txt
        - python -m py_compile *.py models/*.py		# Compile everything
        - PAPIEX_OUTPUT=$PWD/ ./epmt -h			# help path 1
        - PAPIEX_OUTPUT=$PWD/ ./epmt help		# help path 2
        - PAPIEX_OUTPUT=$PWD/ ./epmt -d start 		# Generate prolog
        - PAPIEX_OUTPUT=$PWD/ ./epmt -d source 		# Print shell command
        - PAPIEX_OUTPUT=$PWD/ ./epmt -d run sleep 1	# Run command
        - PAPIEX_OUTPUT=$PWD/ ./epmt -d stop   	  	# Generate epilog and append
        - PAPIEX_OUTPUT=$PWD/ ./epmt -d dump   		# Parse/print job_metadata
        - cp settings_sqllite.py settings.py		# Setup in mem sqlite
        - PAPIEX_OUTPUT=$PWD/ ./epmt -d submit 		# Submit
