version: '3.1'

services:
  # @see https://hub.docker.com/_/postgres/
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  web:
    image: webapp
    build: .
    ports:
      - 5000:5000

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes: 
     - ./data/grafana:/var/lib/grafana
    ports:
     - 3000:3000
