version: '3.1'

services:

  # @see https://hub.docker.com/_/postgres/
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: EPMT
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  notebook:
    image: jupyter/datascience-notebook
    restart: always
    volumes:
      - ./data/jupyter:/home/jovyan/work
      - ./:/epmt  
    ports:
      - 8884:8884
    environment:
      JUPITER_ENABLE_LAB: "yes"

  epmt:
    image: epmt-papiex
    volumes:
      - ./:/epmt  
    depends_on:
      - "db"
#    command: -d submit /epmt/TEST2

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes: 
     - ./data/grafana:/var/lib/grafana
    ports:
     - 3000:3000

#datascience-notebook:
#  image:    jupyter/datascience-notebook
#  volumes:
#        - .:/home/jovyan/work
#        - ${LOCAL_DATASETS}:/home/jovyan/work/datasets
#        - ${LOCAL_MODULES}:/home/jovyan/work/modules
#        - ${LOCAL_SSL_CERTS}:/etc/ssl/notebook
#      ports:
#       - 8888:8888
#     container_name:   jupyter_notebook
#      command: "start-notebook.sh"
# \
#        --NotebookApp.password=${ACCESS_TOKEN} \
#        --NotebookApp.certfile=/etc/ssl/notebook/jupyter.pem"
