version: '3.1'

services:
  # @see https://hub.docker.com/_/postgres/
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: EPMT
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes: 
     - ./data/grafana:/var/lib/grafana
    ports:
     - 3000:3000

  web:
    image: webapp
    build: .
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "main.py"]

  db:
    image: postgres
    ports:
       - 5432:5432
#   notebook:
# #docker run --rm -p 10000:8888 -e JUPYTER_ENABLE_LAB=yes -v "$PWD":/home/jovyan/work jupyter/datascience-notebook:latest
#     image: jupyter/datascience-notebook
#     restart: always
#     volumes:
#      - ./data/jupyter:/home/jovyan/work
#     environment:
#      JUPITER_ENABLE_LAB: yes
#     ports:
#      - 8888:8888
