FROM centos:6

RUN yum update -y
RUN yum install -y make tcsh
RUN yum clean all
RUN rm -rf /var/cache/yum

WORKDIR /home
ARG release
ARG release_tests
ARG settings=settings_sqlite_inmem_sqlalchemy.py
ARG destdir=/opt/epmt

ADD ${release} ${destdir}
WORKDIR /home/epmt-install-tests
ADD ${release_tests} .
COPY preset_settings/${settings} ${destdir}/epmt-install/epmt/settings.py
ENV PATH="${destdir}/epmt-install/epmt:${PATH}"

CMD ["make","check-python-shells"]
