#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER epmt_ro PASSWORD 'b33JFn2X';
    CREATE USER epmt_rw PASSWORD 'Hb79xbwD';
    CREATE USER epmt_admin PASSWORD 'MhwTnx39F';
    CREATE DATABASE EPMT;
    REVOKE CREATE ON SCHEMA public FROM public;

    GRANT ALL PRIVILEGES ON DATABASE EPMT TO epmt_admin;
    GRANT ALL ON SCHEMA public TO epmt_admin;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO epmt_admin;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO epmt_admin;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES to epmt_admin;

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO epmt_rw;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO epmt_rw;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO epmt_rw;
    ALTER DEFAULT PRIVILEGES FOR ROLE epmt_admin GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO epmt_rw;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES to epmt_rw;
    ALTER DEFAULT PRIVILEGES FOR ROLE epmt_admin GRANT ALL ON SEQUENCES to epmt_rw;

    GRANT CONNECT ON DATABASE EPMT TO epmt_ro;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO epmt_ro;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO epmt_ro;
    ALTER DEFAULT PRIVILEGES FOR ROLE epmt_admin GRANT SELECT ON TABLES TO epmt_ro;
EOSQL
