FROM centos:6

WORKDIR /home
RUN yum update -y
RUN yum install -y make tcsh
RUN yum clean all
RUN rm -rf /var/cache/yum

ARG release=2.1.0
ARG settings=settings_sqlite_inmem_sqlalchemy.py
ARG destdir=/opt/epmt
ARG os_target=centos-6

ADD epmt-${release}-${os_target}.tgz ${destdir}
ADD test-epmt-${release}-${os_target}.tgz .
COPY preset_settings/${settings} ${destdir}/epmt-install/epmt/settings.py
WORKDIR /home/epmt-install-tests
ENV PATH="${destdir}/epmt-install/epmt:${PATH}"

# Allow perf events
# RUN echo -e "#!/bin/bash\nmount -o remount rw /proc\nsysctl -w kernel.perf_event_paranoid=0\n\$\*" > /tmp/init.sh
# CMD ["/bin/bash","/tmp/init.sh","make","check-python-shells"]
# Unit tests not supported because python3 and requirements not installed

CMD ["make","check-python-shells"]
