FROM giovtorres/docker-centos7-slurm:latest

WORKDIR /tmp
ARG install_path=/opt/minimalmetrics
ARG epmt_version
ARG epmt_full_release

RUN yum update -y
RUN yum install -y tcsh environment-modules
RUN yum clean all
RUN rm -rf /var/cache/yum

WORKDIR ${install_path}
COPY ${epmt_full_release} .
COPY utils/epmt-installer .
COPY utils/check-release .
RUN echo -ne "\n\n" | ./epmt-installer `basename ${epmt_full_release}`
ENV PATH="${install_path}/epmt-${epmt_version}/epmt-install/epmt:${PATH}"
RUN rm -f *.tgz epmt-installer

