FROM centos:7

RUN yum install -y gcc openssl-devel bzip2-devel libffi-devel bash tcsh nc curl make postgresql-devel && yum clean all

RUN cd /usr/src && echo "downloading python" && curl -o Python-3.7.4.tgz https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz && tar xzf Python-3.7.4.tgz && cd Python-3.7.4 && echo "building python3" && ./configure -q --enable-optimizations && make --silent install > /dev/null

COPY requirements.txt.py3 /tmp/
RUN python3 -V && pip3 install --upgrade pip && pip3 install -r /tmp/requirements.txt.py3
