# FROM centos:7
FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive

# RUN yum update -y
# RUN yum install -y make tcsh
# RUN yum clean all
# RUN rm -rf /var/cache/yum

# update apt, apt-get
RUN apt update -y
RUN apt-get update -y

RUN apt-get install -y make tcsh
#RUN apt clean all
#RUN rm -rf /var/cache/apt

ARG release
ARG release_tests
ARG settings=settings_sqlite_inmem_sqlalchemy.py
ARG destdir=/opt/epmt

WORKDIR /home
ADD ${release}.tgz ${destdir}
WORKDIR /home/epmt-install-tests
ADD ${release_tests}.tgz .
COPY preset_settings/${settings} ${destdir}/epmt-install/epmt/settings.py
ENV PATH="${destdir}/epmt-install/epmt:${PATH}"

CMD ["/bin/bash", "-c", "sysctl kernel.perf_event_paranoid=1; make check-python-shells"]

