FROM phusion/baseimage:0.10.2

COPY ui/requirements-ui.txt.py3 requirements.txt.py3 /tmp
RUN add-apt-repository ppa:deadsnakes/ppa && install_clean python3.7 python3.7-venv python3.7-dev python3-pip python3-setuptools && python3.7 -m pip install --upgrade pip && python3.7 -m pip install -r /tmp/requirements-ui.txt.py3 -r /tmp/requirements.txt.py3 && rm /usr/bin/python3 && ln -s /usr/bin/python3.7 /usr/bin/python3

# ENTRYPOINT ["python"]
# When run without anything, print help
CMD ["python", "-h"]
