FROM python:2.7

COPY requirements.txt /tmp
WORKDIR /tmp
RUN pip install -r requirements.txt
RUN rm -f requirements.txt

# ENTRYPOINT ["python"]
# When run without anything, print help
CMD ["python", "-h"]
