FROM python:3.7.4-alpine

RUN apk add --no-cache bash tcsh netcat-openbsd make build-base postgresql-dev libffi-dev openssl-dev bzip2-dev zlib-dev readline-dev sqlite-dev py3-setuptools

COPY requirements.txt.py3 /tmp
RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt.py3

# ENTRYPOINT ["python3"]
# When run without anything, print python version
CMD ["python3", "-V"]
