FROM python:3.7.4

USER root
WORKDIR /home/dash
ADD requirements-ui.txt.py3 requirements.txt.py3 /home/dash/
RUN pip install --trusted-host pypi.python.org -r requirements-ui.txt.py3 -r requirements.txt.py3

EXPOSE 8050
ENV PYTHONUNBUFFERED 0
CMD ["python","-u","index.py"]
