#!/bin/bash -e

# This script thoroughly tests an EPMT release
# usage:
#
#  utils/check-release 
#  - or -
#  utils/check-release /path/to/EPMT-*.tgz


skip_unittests=0
case $1 in
  --no-unit-tests) skip_unittests=1; shift;;
  --help|help|-h|--h) echo "usage: check-release [--no-unit-tests] [/path/to/EPMT-release-*.tgz]"; exit 0;;
esac

function die() {
  echo $* >&2
  exit 1
}

wait_file() {
  local file="$1"; shift
  local wait_seconds="${1:-10}"; shift # 10 seconds as default timeout

  until test $((wait_seconds--)) -eq 0 -o -f "$file" ; do sleep 1; done

  ((++wait_seconds))
}

verify_staged_file() {
  local tgz="$1"
  local cmd="$2"
  wait_file $tgz 10 || die "$tgz not found"
  test -f $tgz && test -s $tgz
  tar tvf $tgz
  tar xf $tgz
  test -s job_metadata
  test -s *-collated-papiex-*-*.csv
  rm -f job_metadata *-collated-papiex-*-*.csv
  echo "$cmd PASSED"
}

release=${1:-$(ls -1rt EPMT-release-*.tgz| tail -n1)}
release_file=$(basename "$release")
STAGE="/tmp/$(echo $release_file| sed 's/.tgz//')"
OS_TARGET="$(echo $release_file| sed 's/.tgz//; s/EPMT-release-[0-9]-//'| cut -d- -f4-)"
echo "Release OS: $OS_TARGET"
case $OS_TARGET in
  centos-6|centos-7) ;;
  *) die "Do not know how to check release for OS: $OS_TARGET";;
esac

test -n "$release" || die "Could not find a release to test. Looking for EPMT-*.tgz"
test -f "$release" || die "$release does not exist or is not readable"

echo "Testing release: $release"
echo "Staging area: $STAGE"
echo "Wiping clean staging area and recreating it.."; rm -rf "$STAGE"
mkdir -p "$STAGE"

script_dir="$(dirname $0)"
echo "copying epmt-installer and $release to staging area"
cp -v "$script_dir/epmt-installer" "$STAGE"/
cp -v "$release" "$STAGE"/

echo "Changing directory to: $STAGE (staging area)"
cd $STAGE/
pwd
echo; echo "Running epmt-installer.."
echo -e "\n\n" | ./epmt-installer "$release_file" || die "epmt-installer FAILED"
EPMT_PREFIX=$(ls -d "$STAGE"/epmt-*|grep -v installer)
echo "EPMT_PREFIX=$EPMT_PREFIX"
# echo "Prepending $EPMT_PREFIX/epmt-install/epmt to PATH"
export PATH="$EPMT_PREFIX/epmt-install/epmt:$PATH"
echo "epmt: $(which epmt)"
epmt -V || die "Could not execute EPMT"

# cleanup on exit or interrupt
function cleanup() {
  echo;echo "Stopping SLURM test container.."
  docker stop $SLURM_CONTAINER
}

echo;echo "Starting SLURM ($OS_TARGET) test container.."
trap cleanup EXIT INT QUIT HUP TERM
case $OS_TARGET in
  centos-6) SLURM_IMAGE="giovtorres/docker-centos6-slurm:latest";;
  centos-7) SLURM_IMAGE="giovtorres/docker-centos7-slurm:19.05.1";;
esac

SLURM_CONTAINER="$OS_TARGET-slurm-release-test"
docker run --name $SLURM_CONTAINER --rm -dt -h ernie -v $PWD:$PWD:z -w $PWD --privileged -e PATH="$EPMT_PREFIX/epmt-install/epmt:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin" $SLURM_IMAGE tail -f /dev/null
sleep 2
echo;echo "Installing tcsh.."; docker exec $SLURM_CONTAINER yum install -y -q tcsh
docker exec $SLURM_CONTAINER epmt -V
docker exec $SLURM_CONTAINER epmt check

echo;echo "Testing sbatch with epmt-example.?sh"
docker exec $SLURM_CONTAINER sbatch "$EPMT_PREFIX/epmt-install/epmt/epmt-example.sh"
verify_staged_file 2.tgz "sbatch epmt-example.sh"
docker exec $SLURM_CONTAINER sbatch "$EPMT_PREFIX/epmt-install/epmt/epmt-example.csh"
verify_staged_file 3.tgz "sbatch epmt-example.csh"

echo;echo "Testing srun --task-prolog/task-epilog"
docker exec $SLURM_CONTAINER srun -n1 --task-prolog="$EPMT_PREFIX/epmt-install/slurm/slurm_task_prolog_epmt.sh" --task-epilog="$EPMT_PREFIX/epmt-install/slurm/slurm_task_epilog_epmt.sh" sleep 1
verify_staged_file 4.tgz "srun --task-prolog/task-epilog sleep 1"

echo;echo "Testing auto-instrumentation by adding prolog/epilog to slurm.conf"
docker exec $SLURM_CONTAINER bash -c "echo TaskProlog=$EPMT_PREFIX/epmt-install/slurm/slurm_task_prolog_epmt.sh >> /etc/slurm/slurm.conf"
docker exec $SLURM_CONTAINER bash -c "echo TaskEpilog=$EPMT_PREFIX/epmt-install/slurm/slurm_task_epilog_epmt.sh >> /etc/slurm/slurm.conf"
docker exec $SLURM_CONTAINER scontrol reconfigure
echo -e "#!/bin/tcsh\nsleep 1\n" > uninstr.csh
docker exec $SLURM_CONTAINER sbatch uninstr.csh
verify_staged_file 5.tgz "sbatch with auto-instrument using prolog/epilog"

# case $OS_TARGET in
#   centos-6) echo "Skipping integration and unit tests for $OS_TARGET"; exit 0;;
# esac
  
echo;echo "Running integration tests (in SLURM container)"
docker exec $SLURM_CONTAINER bash -c "rm -f /root/EPMT_DB.*; cd $EPMT_PREFIX/epmt-install/epmt; test/integration/run_integration"

if [ $skip_unittests -eq 1 ]; then
  echo;echo "skipping unit tests as invoked with --no-unit-tests option"
else
  echo;echo "Running unit tests (in SLURM container)"
  docker exec $SLURM_CONTAINER bash -c "rm -f /root/EPMT_DB.*; epmt unittest"
fi

exit 0
