#!/bin/bash

# this script drops all tables in the EPMT database.
# We should remove this script once we have ./epmt --drop working!
echo "Dropping all tables in EPMT database.."
PGPASSWORD=example psql -U postgres -h postgres EPMT <<-'END_SQL'
        DO $$ DECLARE
            r RECORD;
        BEGIN
            -- if the schema you operate on is not "current", you will want to
            -- replace current_schema() in query with 'schematodeletetablesfrom'
            -- *and* update the generate 'DROP...' accordingly.
            FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = current_schema()) LOOP
                EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
            END LOOP;
        END $$;
END_SQL

