#!/bin/bash

function die() {
  echo $* >&2
  exit 1
}

version=$(grep VERSION Makefile| head -n 1| cut -f2 -d=); [ "$version" != "" ] || die "could not determine version"
target=$(grep OS_TARGET Makefile| head -n 1| cut -f2 -d=); [ "$target" != "" ] || die "could not determine target"
release_tar="EPMT-release-$version-$target.tgz"

[ ! -f $release_tar ] || die "Release file $release_tar already exists. Please remove it and try again"

no_build=0
case $1 in
  --no-build) echo "Using existing tar files; not building anything new"; no_build=1;;
esac


echo "Making EPMT release $version for $target..."

if [ $no_build -eq 0 ]; then
    echo " - building epmt and epmt-test tarball"
    make docker-dist > /dev/null
fi
epmt_tar=$(ls epmt-$version.tgz); [ -f "$epmt_tar" ] || die "Could not find epmt-$version.tgz"
epmt_test_tar=$(ls test-epmt-$version.tgz); [ -f "$epmt_test_tar" ] || die "Could not find test-epmt-$version.tgz"
echo " - using $epmt_tar and $epmt_test_tar"

if [ $no_build -eq 0 ]; then
    echo " - building papiex tarball"
    (cd ../papiex-oss; make docker-dist > /dev/null; cp -v papiex-epmt-*.tgz ../epmt/papiex-epmt-$version.tgz)
fi
papiex_tar=$(ls papiex-epmt-$version.tgz); [ -f "$papiex_tar" ] || die "Could not find papiex-epmt-$version.tgz"
echo " - found $papiex_tar"

echo "Assembling release tarball"
tar -czf $release_tar $epmt_tar $epmt_test_tar $papiex_tar
echo "Release prepared: $release_tar"
