site_name: Experiment Performance Management Tool (EPMT)
theme:
  name: bootstrap4
  favicon: favicon.ico
  logo: logo.png
  palette:
    primary: blue
    accent: grey
  navigation_depth: 2
  include_search_page: true
  search_index_only: false

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

use_directory_urls: false

nav:
  - EPMT Quick Start: Quickstart.md
  - EPMT Install: INSTALL.md
  - EPMT Readme: README.md
  - EPMT Explore Command: epmt-explore-cli.md
  - EPMT Commands: epmt_cmds.md
  - migrations.md
  - db-multiple-users.md
  - Notebooks: 
    - Outliers: http://localhost:8888/notebooks/Outliers.ipynb" target="_blank
    - Query API: http://localhost:8888/notebooks/Query-API.ipynb" target="_blank
    - Graphing API: http://localhost:8888/notebooks/Graphing-API.ipynb" target="_blank
  - EPMT Workflow GUI: http://localhost:8050" target="_blank
  - EPMT Workflow GUI Readme: index_ui.md
  - Release Notes: RELEASE_NOTES.md
