site_name: EPMT
theme:
  name: material
  favicon: favicon.ico
  logo: logo.png
  palette:
    primary: blue
    accent: grey
  navigation_depth: 2
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
plugins: []
use_directory_urls: false

nav:
  - EPMT Install: INSTALL.md
  - EPMT Readme: README.md
  - EPMT Commands: epmt_cmds.md
  - migrations.md
  - Notebooks: 
    - Outliers: http://localhost:8888/notebooks/notebooks/Outliers.ipynb" target="_blank
    - Query API: http://localhost:8888/notebooks/notebooks/Query-API.ipynb" target="_blank
    - Graphing API: http://localhost:8888/notebooks/notebooks/graphing.ipynb" target="_blank
  - Interface: http://localhost:8050" target="_blank
  - Interface Readme: index_ui.md