from setuptools import setup
#setup()
setup(name              = "epmt",
      version           = "4.10.0",
      packages          = [ 'epmt'],
      package_dir       = {'epmt' : 'epmt' },
#      package_data      = {'lib' : [ 'papiex-epmt-install/lib/*so*' ] },
      data_files        = [ ('lib/python3.9/site-packages/epmt/lib',
                             [ 'papiex-epmt-install/lib/libmonitor.so',
                               'papiex-epmt-install/lib/libmonitor.so.0.0.0',
                               'papiex-epmt-install/lib/libpapi.a',
                               'papiex-epmt-install/lib/libpapiex.so.2',
                               'papiex-epmt-install/lib/libpapi.so',
                               'papiex-epmt-install/lib/libpapi.so.5.7.0',
                               'papiex-epmt-install/lib/libpfm.a',
                               'papiex-epmt-install/lib/libpfm.so.4',
                               'papiex-epmt-install/lib/libmonitor.so.0',
                               'papiex-epmt-install/lib/libmonitor_wrap.a',
                               'papiex-epmt-install/lib/libpapiex.so',
                               'papiex-epmt-install/lib/libpapiex.so.2.3.14',
                               'papiex-epmt-install/lib/libpapi.so.5',
                               'papiex-epmt-install/lib/libpapi.so.5.7.0.0',
                               'papiex-epmt-install/lib/libpfm.so',
                               'papiex-epmt-install/lib/libpfm.so.4.10.1',
                              ] ),
                            ('lib/python3.9/site-packages/epmt/bin',
                             [ 'papiex-epmt-install/bin/check_events',
                               'papiex-epmt-install/bin/monitor-link',
                               'papiex-epmt-install/bin/monitor-run',
                               'papiex-epmt-install/bin/papi_avail',
                               'papiex-epmt-install/bin/papi_command_line',
                               'papiex-epmt-install/bin/papi_component_avail',
                               'papiex-epmt-install/bin/papi_native_avail',
                               'papiex-epmt-install/bin/showevtinfo',
                              ] ) ],
      scripts           = [ 'scripts/epmt' ],
      )
