
def name():
    fl = ["Icedance", "Castlewaltz", "Allroom", "Poledance", "Irisdango", "Harlemsham", "Lyricalypso", "Lamenco", "Flambo", "Slowning", "Clubdanse", "Harddancing", "Hipdance", "Robushki", "Bollydance", "Stillion", "Westep", "Breakdance", "Contrydance", "Stilet", "Handance", "Caldance", "Bassanova", "Irisdance", "Erotilet", "Conce", "Electroika", "Snapdancing", "Cajunwalk", "Cakewaltz", "Cripwaltz", "Freakdance", "Histon", "Freestep", "Drobotdance", "Harddango", "Moonwalk", "Affrance", "Modernswing", "Tapdanging", "Twoston", "Zumbadance", "Hiphop", "Mambethwalk", "Stepdancing", "Irisdanse", "Hokey", "Coticdance", "Bostep", "Sambo", "Ballemande",
          "Rhumbadance", "Fande", "Cossanova", "Fandledanse", "Headbango", "Bassance", "Ethwalk", "Trotillion", "Foxtrotilet", "Marimbo", "Cripwalker", "Foxtrodance", "Chumbadance", "Freakaway", "Handdance", "Shimshake", "Raindance", "Mamba", "Slowwalk", "Macarer", "Mambadance", "Huladancing", "Lambo", "Ballemshake", "Snapdango", "Tanging", "Moonwaltz", "Freestyle", "Foxtroika", "Candance", "Fandjive", "Bombadance", "Cotilet", "Pogodanchi", "Bostepdance", "Limbadance", "Fanddance", "Cajunjive", "Morrisdango", "Pogodanse", "Firedancing", "Cossadance", "Cance", "Cajunwalker", "Lationdance", "Freetdance", "Tapdancing", "Lamba", "Mediving"]
    sl = ["Dishdraine", "Hairfryer", "Airiron", "Disher", "Sewingfan", "Oiler", "Multicfan", "Crepot", "Press", "Hairion", "Hairioner", "Cornmangle", "Foodster", "Aircooker", "Icecooker", "Ricebox", "Stoven", "Aromachine", "Airionoven", "Cornmaker", "Hotplater", "Airdryer", "Airion", "Pancaker", "Pationoven", "Mouser", "Airioner", "Pationiser", "Dishwashine", "Pation", "Washer", "Espress", "Convection", "Refryer", "Popcornman", "Airionove", "Atticooker", "Washine", "Toasteamer", "Aircondryer", "Wingfan", "Fanheate", "Icepot",
          "Water", "Ricepot", "Hairioniser", "Haircooker", "Boxman", "Waterheate", "Pationove", "Hairionoven", "Wingmachine", "Trouser", "Pationer", "Washiner", "Crepolisher", "Sewindowfan", "Condryer", "Firepemaker", "Wateroven", "Trousetrap", "Patioheate", "Hairionove", "Waterove", "Riceboxman", "Icepolisher", "Airironman", "Washingfan", "Ironmaker", "Disherdryer", "Aromachiner", "Ironmangle", "Futondition", "Mouserpress", "Foodsterove", "Cornman", "Oilheate", "Iceboxman", "Condition", "Hairironman", "Conditioner", "Toasterove"]
    tl = ["Caroll", "Hotbrot", "Icecread", "Bansandwich", "Fairyburger", "Limburger", "Bream", "Bagel", "Cheesedread", "Chiburger", "Eggsaltbeef", "Ausandwich", "Letsandwich", "Terroll", "Jucyburger", "Omelette", "Horsandwich", "Roast", "Butte", "Ausagel", "Sandwich", "Butty", "Pastie", "Chipbun", "Sausandwich", "Hawaii", "Denvern", "Butterroll", "Ricsandwich", "Teakbomb", "Patty", "Curris", "Steak", "Saltbeef", "Breakbomb", "Pasthawaii", "Diaburger", "Baconshire", "Loburger", "Sloppedbeef", "Cubanquetta", "Anguetbutte", "Chipbutte", "Gersandwich", "Chileburger", "Break", "Bread", "Greenchdip", "Pulledpork", "Gatsandwich", "Donkebab", "Sterburger",
          "Terburger", "Turkebab", "Chopbutte", "Buffuletta", "Friedbeef", "Chimich", "Breakfastie", "Spaghetta", "Veggs", "Cornedbeef", "Bunkebab", "Steakfast", "Iceburger", "Faloburger", "Roastie", "Generkebab", "Lobsteak", "Fairybream", "Omelt", "Naanbeef", "Buffalafel", "Tonguetta", "Tofusagel", "Eggsalafel", "Eggieburger", "Muffulette", "Salafel", "Banquetta", "Hamchimich", "Peanutbutte", "Letta", "Hotturkebab", "Icecream", "Baguetbutty", "Baguetoast", "Letterroll", "Fairybreak", "Roastbeef", "Kimchimich", "Tersandwich", "Roasthawaii", "Peanutbutty", "Veggsalafel", "Chimichloaf", "Buttymelt", "Frenchipbun", "Toastbrot", "Manwichwrap"]
    from random import choice, getrandbits
    return choice(fl) + " " + choice(sl) + ('-' if bool(getrandbits(1)) else ' ') + choice(tl)


class name_gen:
    def __init__(self):
        self.name = name()
